volumes:
  pg_data:
  static:

services:
  db:
    restart: unless-stopped
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    restart: unless-stopped
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    restart: unless-stopped
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static:/frontend_static
  gateway:
    restart: unless-stopped
    build: ./gateway/
    env_file: .env
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static